language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    #- clang
    - libpng12-dev
    #- libjpeg-dev
    #- libmagick++-dev
    #- libgraphicsmagick++1-dev
    #- libfftw3-dev
    #- zlib1g-dev
git:
    # handle git submodules yourself
    submodules: false
before_install:
    # use sed to replace the SSH URL with the public URL, then initialize submodules
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
script:
  # build dependencies
  - ./configure --disable-video-hash --disable-audio-hash CXXFLAGS="-I$TRAVIS_BUILD_DIR/lib/CImg" LDFLAGS="-lpthread"
  # build pHash lib
  - make CXX='g++-4.8'
