refimage: 

population:
    numindividuals: 10
    elitecount: 2

image:
    minpolys: 20
    maxpolys: 60

polygon:
    minpoints: 3
    maxpoints: 10

mutation:
    image:
        addpoly: 0.05
        removepoly: 0.05
        swappolys: 0.05
        backgroundcolor: 0.05
    polygon:
        addpoint: 0.05
        removepoint: 0.05
        changecolor: 0.05
    point:
        move: 0.000000000000001
