#refimage:  "/path/to/ref/img.png"

population:
    numindividuals: 5
    elitecount: 1

image:
    minpolys: 30
    maxpolys: 50

polygon:
    minpoints: 3
    maxpoints: 8

mutation:
    image:
        addpoly: 0.01
        removepoly: 0.01
        swappolys: 0.01
    polygon:
        addpoint: 0.01
        removepoint: 0.01
        changecolor: 0.01
    point:
        move: 0.01
