refimage: 

image:
    minpolys: 20
    maxpolys: 60

polygon:
    minpoints: 3
    maxpoints: 10

mutation:
    polygon:
        add: 0.05
        remove: 0.05
        swap: 0.05
        color: 0.05
    point:
        add: 0.05
        remove: 0.05
